### ISSUE TITLE
Layout is styled like National Brain Tumor Society

### ISSUE THREAD

**Issue by mwenger1** [mwenger1/trial-match#16]
- [ ] Layout/Wrapper mirrors [National Brain Tumor Website](http://braintumor.org/)

**Comment by opihana** [comment]
Is the idea to use the NBTS website as the prime / white-label version? Or is the idea to be able to add NBTS styles to a prime version?

**Comment by mwenger1** [comment]
Curious what you think. My thought is that if another group wanted to spin up the site, they would fork, have separate ENV variables, and modify the layout file to include their site's content.

That way this repo will be NBTS specific.

We can always revisit that architecture decision in the future when/if another group wants their own instance of the application.
