### ISSUE TITLE
Nightly import service for clinicaltrials.gov

### ISSUE THREAD

**Issue by mwenger1** [mwenger1/trial-match#3]
- [x] Application can be configured to fetches trials from [clinicaltrials.gov](https://clinicaltrials.gov/) by condition and no_unk
- [x] New trials in clinicaltrials.gov are created as new Trial records
- [x] A trials sites in clinicaltrials.gov are created as new Site records
- [x] Trials are not imported if there have been no changes since last import
- [x] Modified trials in clinicaltrials.gov update the values for a Trial record
- [x] Service runs nightly

**Comment by opihana** [comment]
@mwenger1 will you indicate that you are currently working on an issue by assigning it to yourself? Want to avoid overlap.

**Comment by mwenger1** [comment]
@opihana will do!
