### ISSUE TITLE
Searching by Location

### ISSUE THREAD

**Issue by mwenger1** [mwenger1/trial-match#54]
The index view displays the nearest site location.

Problem:

* It blurs in with the rest of the text.
* Doesn't highlight the distance away.

---------------------------------
<img width="578" alt="screen shot 2016-09-05 at 11 02 11 am" src="https://cloud.githubusercontent.com/assets/1781967/18251671/5d87d320-7358-11e6-9b95-7c1f2f9501f7.png">

---------------------------------
<img width="1059" alt="screen shot 2016-09-05 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/1781967/18251672/5d89c0cc-7358-11e6-8b01-957ea69400bc.png">

**Comment by mwenger1** [comment]
@opihana another area in need of major design improvement

**Comment by opihana** [comment]
@mwenger1 I think the bigger problem with this content is that the user will believe that this is the only site location. Many users will not know that studies have multiple site locations. A couple of questions:

1. Is it important for the user to see the site location on the index view?
2. If so, is it the most important piece of information? What is the biggest piece of information that would convince a user to participate in a study? Will they participate in any study as long as it's nearby, or will they participate in a specific type of study, no matter how far?
3. WDUTA adding a subheader, like "12 site locations with the nearest one at:" 

If you like # 3 I can make a mockup. Wanted your feedback first.

**Comment by opihana** [comment]
@mwenger1 This is how I picture it. I'd like to update the "Learn more" buttons to look less like a toggle and more like a button, but I'll make that a separate issue.

<img width="482" alt="screen shot 2016-09-06 at 2 10 07 pm" src="https://cloud.githubusercontent.com/assets/6323933/18285291/bcfa60c8-743b-11e6-9dd3-ae8a18af69e0.png">

**Comment by mwenger1** [comment]
I like the icons 👍 .

I would imagine it's helpful to know that something is 5 miles away vs 95 miles away to make it more enticing to click into it. I could also see it being more enticing to click on it if the nearby location is well known to the user and credible (i.e. New York Presbyterian Hospital). I do hear you about the concern if someone doesn't realize there are more sites. I like your approach with 3. Maybe something like:
```
{icon} Weill Cornell Medical College (+ 15 other site locations)
```

As for other helpful details on the index page, I think observational vs interventional could be another item for us to highlight (and possibly add as a filter).
